/**
 * Passive tree geometry and art bindings from PoB's TreeData/<version>/tree.json,
 * mirroring PassiveTree.lua: node positions from group + orbit angle tables,
 * connector arcs from BuildConnector, art sizes from GetNodeTargetSize.
 *
 * PoE2's tree.json is read as is. PoE1's (generated by pob-sync from tree.lua)
 * carries the older schema, which `normalisePoe1` folds into the same shape.
 */

import type { DynamicGroup, DynamicNode } from "$lib/engine.svelte";

export type NodeKind = "normal" | "notable" | "keystone" | "socket" | "mastery" | "classStart" | "ascStart" | "onlyImage";

export interface NodeOverlay {
  alloc: string;
  path: string;
  unalloc: string;
}

export interface AttributeOption {
  name: string;
  icon: string;
  stats: string[];
}

export interface TNode {
  id: number;
  name: string;
  stats: string[];
  x: number;
  y: number;
  kind: NodeKind;
  asc: string | null;
  classesStart: string[] | null;
  group: number;
  orbit: number;
  icon: string;
  /** PoE1 masteries swap to this icon once allocated. */
  activeIcon: string | null;
  /** PoE1 masteries: the effects on offer, for the tooltip. */
  masteryEffects: { effect: number; stats: string[] }[] | null;
  links: number[];
  flavour: string | null;
  switchable: boolean;
  isAttribute: boolean;
  options: AttributeOption[] | null;
  overlay: NodeOverlay | null;
  effect: string | null;
  /** Half extents in tree units (PoB draws 2× these). */
  size: { base: number; overlay: number; effect: number };
  /** Hit radius; 0 = not hoverable. */
  r: number;
  hidden: boolean;
}

export interface Arc {
  cx: number;
  cy: number;
  r: number;
  a1: number;
  a2: number;
  ccw: boolean;
}

export interface TEdge {
  a: number;
  b: number;
  asc: string | null;
  arc: Arc | null;
}

export interface TAscendancy {
  name: string;
  id: string;
  bg: string;
  x: number;
  y: number;
  half: number;
  /** PoE2 variants: this plate stands in for `replace` while chosen, and hides when `replaceBy` is. */
  replace: string | null;
  replaceBy: string | null;
}

export interface TClass {
  name: string;
  id: number;
  bg: string;
  bgX: number;
  bgY: number;
  bgHalf: number;
  activeHalf: number;
  ringHalf: number;
  /** The hub plate switches to the chosen ascendancy's art (PoE2); PoE1 draws that at the ascendancy instead. */
  hubAsc: boolean;
  /** PoE1's class illustration, drawn at PoB's fixed spot when the class is current. */
  area: { bg: string; x: number; y: number } | null;
  ascendancies: TAscendancy[];
  startNode: number | null;
}

/** PoE1 group ring art; `mirrored` is PoB's half image drawn twice, top and flipped. */
export interface TGroupArt {
  x: number;
  y: number;
  bg: string;
  mirrored: boolean;
}

export interface TreeModel {
  version: string;
  poe1: boolean;
  nodes: Map<number, TNode>;
  edges: TEdge[];
  classes: TClass[];
  groups: TGroupArt[];
  classStart: Map<string, number>;
  bounds: { minX: number; minY: number; maxX: number; maxY: number };
}

// PassiveTreeView.lua draws these at fixed tree coordinates per class id.
const POE1_AREA: Record<number, { bg: string; x: number; y: number }> = {
  1: { bg: "BackgroundStr", x: -2750, y: 1600 },
  2: { bg: "BackgroundDex", x: 2550, y: 1600 },
  3: { bg: "BackgroundInt", x: -250, y: -2200 },
  4: { bg: "BackgroundStrDex", x: -150, y: 2350 },
  5: { bg: "BackgroundStrInt", x: -2100, y: -1500 },
  6: { bg: "BackgroundDexInt", x: 2350, y: -1950 },
};

interface RawNode {
  skill: number;
  name: string;
  icon: string;
  stats: string[];
  group: number;
  orbit: number;
  orbitIndex: number;
  connections: { id: number; orbit: number }[];
  isNotable?: boolean;
  isKeystone?: boolean;
  isJewelSocket?: boolean;
  isOnlyImage?: boolean;
  isAttribute?: boolean;
  isAscendancyStart?: boolean;
  isSwitchable?: boolean;
  containJewelSocket?: boolean;
  ascendancyName?: string;
  classesStart?: string[];
  flavourText?: string;
  aliasPassiveSocket?: string;
  nodeOverlay?: NodeOverlay;
  activeEffectImage?: string;
  options?: unknown;
  // PoE1 (tree.lua) fields
  out?: (string | number)[];
  classStartIndex?: number;
  isMastery?: boolean;
  isProxy?: boolean;
  isBlighted?: boolean;
  /** Cluster socket; `parent` marks a sub-socket that only exists inside a socketed cluster. */
  expansionJewel?: { size?: number; index?: number; proxy?: string | number; parent?: string | number } | null;
  activeIcon?: string;
  inactiveIcon?: string;
  masteryEffects?: { effect: number; stats: string[] }[];
  isBloodline?: boolean;
}

interface RawBackground {
  image: string;
  x: number;
  y: number;
  width: number;
  height: number;
  active?: { width: number; height: number };
  bg?: { width: number; height: number };
}

interface RawTree {
  nodes: Record<string, RawNode>;
  // sparse: unused group ids are null
  groups: ({ x: number; y: number; orbits: number[]; nodes: (number | string)[] } | null)[];
  constants: { orbitRadii: number[]; skillsPerOrbit: number[]; orbitAnglesByOrbit: number[][] };
  classes: {
    name: string;
    integerId: number;
    background?: RawBackground;
    ascendancies: { id: string; name: string; internalId: string; background?: RawBackground; replace?: string; replaceBy?: string }[];
  }[];
  nodeOverlay: Record<string, NodeOverlay>;
  min_x: number;
  min_y: number;
  max_x: number;
  max_y: number;
  poe1?: boolean;
  // PoE1: class-independent ascendancies (Warden, the bloodlines)
  alternate_ascendancies?: { id: string; name: string }[];
  bloodline?: Set<string>;
}

function targetSize(rn: RawNode, kind: NodeKind): { base: number; overlay: number; effect: number } {
  if (rn.isAscendancyStart) return { base: 0, overlay: 50, effect: 0 };
  if (kind === "normal" && rn.ascendancyName) return { base: 37, overlay: 80, effect: 0 };
  if (rn.containJewelSocket) return { base: 80, overlay: 80, effect: 0 };
  if (rn.ascendancyName) return { base: 54, overlay: 100, effect: 0 };
  switch (kind) {
    case "notable":
      return { base: 54, overlay: 80, effect: 380 };
    case "onlyImage":
      return { base: 380, overlay: 0, effect: 0 };
    case "keystone":
      return { base: 82, overlay: 120, effect: 380 };
    case "normal":
      return { base: 37, overlay: 54, effect: 0 };
    case "socket":
      return { base: 76, overlay: 76, effect: 0 };
    case "classStart":
      return { base: 37, overlay: 1, effect: 0 };
    default:
      return { base: 0, overlay: 0, effect: 0 };
  }
}

// PoE1's PassiveTreeView draws every sprite at its sheet size × 1.33, so the
// half extents are the 3.19+ sprite widths (37 px icons, 39/58/84 px frames)
// times that factor.
const P1 = 1.33;
function targetSizePoe1(rn: RawNode, kind: NodeKind): { base: number; overlay: number; effect: number } {
  if (rn.isAscendancyStart) return { base: 0, overlay: 31 * P1, effect: 0 };
  if (rn.ascendancyName) return kind === "notable" ? { base: 37 * P1, overlay: 61 * P1, effect: 0 } : { base: 37 * P1, overlay: 39 * P1, effect: 0 };
  switch (kind) {
    case "notable":
      return { base: 37 * P1, overlay: 58 * P1, effect: 0 };
    case "keystone":
      return { base: 53 * P1, overlay: 84 * P1, effect: 0 };
    case "normal":
      return { base: 37 * P1, overlay: 39 * P1, effect: 0 };
    case "socket":
      return rn.expansionJewel ? { base: 76 * P1, overlay: 76 * P1, effect: 0 } : { base: 58 * P1, overlay: 58 * P1, effect: 0 };
    case "mastery":
      return { base: 86 * P1, overlay: 0, effect: 297 * P1 };
    case "classStart":
      return { base: 37, overlay: 1, effect: 0 };
    default:
      return { base: 0, overlay: 0, effect: 0 };
  }
}

const POE1_OVERLAY: Record<string, NodeOverlay> = {
  Normal: { alloc: "PSSkillFrameActive", path: "PSSkillFrameHighlighted", unalloc: "PSSkillFrame" },
  Notable: { alloc: "NotableFrameAllocated", path: "NotableFrameCanAllocate", unalloc: "NotableFrameUnallocated" },
  Keystone: { alloc: "KeystoneFrameAllocated", path: "KeystoneFrameCanAllocate", unalloc: "KeystoneFrameUnallocated" },
  Socket: { alloc: "JewelFrameAllocated", path: "JewelFrameCanAllocate", unalloc: "JewelFrameUnallocated" },
};
const POE1_ASC_SMALL: NodeOverlay = { alloc: "AscendancyFrameSmallAllocated", path: "AscendancyFrameSmallCanAllocate", unalloc: "AscendancyFrameSmallNormal" };
const POE1_ASC_LARGE: NodeOverlay = { alloc: "AscendancyFrameLargeAllocated", path: "AscendancyFrameLargeCanAllocate", unalloc: "AscendancyFrameLargeNormal" };
const POE1_BLIGHTED: NodeOverlay = { alloc: "BlightedNotableFrameAllocated", path: "BlightedNotableFrameCanAllocate", unalloc: "BlightedNotableFrameUnallocated" };
const POE1_SOCKET_ALT: NodeOverlay = { alloc: "JewelSocketAltActive", path: "JewelSocketAltCanAllocate", unalloc: "JewelSocketAltNormal" };
const POE1_START_ART = ["centerscion", "centermarauder", "centerranger", "centerwitch", "centerduelist", "centertemplar", "centershadow"];

/** PassiveTree.lua CalcOrbitAngles: 16- and 40-node orbits are irregular. */
function orbitAnglesFor(n: number): number[] {
  let deg: number[];
  if (n === 16) deg = [0, 30, 45, 60, 90, 120, 135, 150, 180, 210, 225, 240, 270, 300, 315, 330];
  else if (n === 40) {
    deg = [0, 10, 20, 30, 40, 45, 50, 60, 70, 80, 90, 100, 110, 120, 130, 135, 140, 150, 160, 170, 180, 190, 200, 210, 220, 225, 230, 240, 250, 260, 270, 280, 290, 300, 310, 315, 320, 330, 340, 350];
  } else deg = Array.from({ length: n }, (_, i) => (360 * i) / n);
  return deg.map((d) => (d * Math.PI) / 180);
}

function prefixed(o: NodeOverlay, prefix: string): NodeOverlay {
  return { alloc: prefix + o.alloc, path: prefix + o.path, unalloc: prefix + o.unalloc };
}

/** Frames for a PoE1 node; bloodline ascendancies carry their own set, named "<Ascendancy><Frame>". */
function poe1Overlay(rn: RawNode, kind: NodeKind, bloodline?: Set<string>): NodeOverlay | null {
  if (rn.ascendancyName) {
    const prefix = bloodline?.has(rn.ascendancyName) ? rn.ascendancyName : "";
    if (kind === "ascStart") return prefixed({ alloc: "AscendancyMiddle", path: "AscendancyMiddle", unalloc: "AscendancyMiddle" }, prefix);
    if (kind === "notable") return prefixed(POE1_ASC_LARGE, prefix);
    if (kind === "normal") return prefixed(POE1_ASC_SMALL, prefix);
  }
  if (kind === "notable" && rn.isBlighted) return POE1_BLIGHTED;
  if (kind === "socket" && rn.expansionJewel) return POE1_SOCKET_ALT;
  const key = kind === "normal" ? "Normal" : kind === "notable" ? "Notable" : kind === "keystone" ? "Keystone" : kind === "socket" ? "Socket" : null;
  return key ? POE1_OVERLAY[key] : null;
}

/**
 * Fold tree.lua's schema into tree.json's: `out` id lists become connections,
 * `classStartIndex` a class name, orbit angles are computed, and the art
 * bindings PoE1 keeps in PassiveTree.lua are attached to the tree.
 */
function normalisePoe1(raw: RawTree) {
  raw.poe1 = true;
  raw.constants.orbitAnglesByOrbit = raw.constants.skillsPerOrbit.map(orbitAnglesFor);
  raw.nodeOverlay = POE1_OVERLAY;
  for (const g of Object.values(raw.groups)) {
    if (g) g.nodes = g.nodes.map(Number);
  }
  raw.classes.forEach((c, i) => {
    c.integerId = i;
    c.ascendancies = c.ascendancies ?? [];
  });
  const ascStart = new Map<string, RawNode>();
  raw.bloodline = new Set((raw.alternate_ascendancies ?? []).map((a) => a.id));
  for (const rn of Object.values(raw.nodes)) {
    if (rn.out && !rn.connections) rn.connections = rn.out.map((o) => ({ id: Number(o), orbit: 0 }));
    if (rn.classStartIndex !== undefined) {
      const c = raw.classes[rn.classStartIndex];
      if (c) rn.classesStart = [c.name];
    }
    if (rn.isAscendancyStart && rn.ascendancyName) ascStart.set(rn.ascendancyName, rn);
    if (rn.isBloodline && rn.ascendancyName) raw.bloodline.add(rn.ascendancyName);
  }
  // tree.lua group ids are 1-based while the array is not; membership decides.
  const groupOf = (rn: RawNode) => {
    const a = raw.groups[rn.group - 1];
    if (a?.nodes?.includes(rn.skill)) return a;
    const b = raw.groups[rn.group];
    if (b?.nodes?.includes(rn.skill)) return b;
    return a ?? b ?? null;
  };
  // The ascendancy plate sits on its start node. Sheets are 0.3835× the
  // 1300 px source, drawn at ×1.33.
  for (const c of raw.classes) {
    const start = Object.values(raw.nodes).find((n) => n.classesStart?.includes(c.name));
    if (start) {
      const g = groupOf(start);
      if (g) c.background = { image: POE1_START_ART[c.integerId] ?? "", x: g.x, y: g.y, width: 241 * P1, height: 241 * P1 };
    }
    for (const a of c.ascendancies) {
      const s = ascStart.get(a.id);
      const g = s ? groupOf(s) : null;
      if (g) a.background = { image: `Classes${a.id}`, x: g.x, y: g.y, width: 1300 * 0.3835 * P1, height: 1300 * 0.3835 * P1 };
    }
  }
  // Class-independent ascendancies get a class of their own so their plates
  // draw with the others. Their art is 1488 px wide.
  if (raw.alternate_ascendancies?.length) {
    const alt = raw.alternate_ascendancies
      .map((a) => {
        const s = ascStart.get(a.id);
        const g = s ? groupOf(s) : null;
        const background = g ? { image: `Classes${a.id}`, x: g.x, y: g.y, width: 1488 * 0.3835 * P1, height: 1412 * 0.3835 * P1 } : undefined;
        return { id: a.id, name: a.name, internalId: a.id, background };
      });
    raw.classes.push({ name: "alternate_ascendancies", integerId: -1, ascendancies: alt });
  }
}

function overlayType(kind: NodeKind): string | null {
  switch (kind) {
    case "normal":
      return "Normal";
    case "notable":
      return "Notable";
    case "keystone":
      return "Keystone";
    case "socket":
      return "Socket";
    default:
      return null;
  }
}

/** Shorter arc from a to b on the circle (cx, cy, r), in canvas terms. */
function minorArc(cx: number, cy: number, r: number, ax: number, ay: number, bx: number, by: number): Arc {
  const a1 = Math.atan2(ay - cy, ax - cx);
  const a2 = Math.atan2(by - cy, bx - cx);
  let d = a2 - a1;
  while (d > Math.PI) d -= Math.PI * 2;
  while (d < -Math.PI) d += Math.PI * 2;
  return { cx, cy, r, a1, a2, ccw: d < 0 };
}

export function parseTree(version: string, json: string): TreeModel {
  const raw = JSON.parse(json) as RawTree;
  if (!raw.constants.orbitAnglesByOrbit) normalisePoe1(raw);
  const poe1 = raw.poe1 === true;
  const { orbitRadii, orbitAnglesByOrbit } = raw.constants;

  // tree.json ships groups as a JSON array while PoB reads it as a 1-based
  // Lua table; detect which convention node.group follows.
  const groupsArr = raw.groups;
  let oneBased = 0;
  let zeroBased = 0;
  for (const n of Object.values(raw.nodes)) {
    if (groupsArr[n.group - 1]?.nodes?.includes(n.skill)) oneBased++;
    else if (groupsArr[n.group]?.nodes?.includes(n.skill)) zeroBased++;
    if (oneBased + zeroBased > 200) break;
  }
  const gidx = (g: number) => (oneBased >= zeroBased ? g - 1 : g);

  const nodes = new Map<number, TNode>();
  const classStart = new Map<string, number>();

  for (const rn of Object.values(raw.nodes)) {
    const g = groupsArr[gidx(rn.group)];
    if (!g) continue;
    const angle = orbitAnglesByOrbit[rn.orbit]?.[rn.orbitIndex] ?? 0;
    const r = orbitRadii[rn.orbit] ?? 0;
    const x = g.x + Math.sin(angle) * r;
    const y = g.y - Math.cos(angle) * r;

    let kind: NodeKind = "normal";
    if (rn.classesStart) kind = "classStart";
    else if (rn.isAscendancyStart) kind = "ascStart";
    else if (rn.isOnlyImage) kind = "onlyImage";
    else if (rn.isJewelSocket) kind = "socket";
    else if (rn.isMastery) kind = "mastery";
    else if (rn.isKeystone) kind = "keystone";
    else if (rn.isNotable) kind = "notable";

    if (rn.classesStart) for (const c of rn.classesStart) classStart.set(c, rn.skill);

    const size = poe1 ? targetSizePoe1(rn, kind) : targetSize(rn, kind);
    const otype = overlayType(kind);
    const overlay = poe1 ? poe1Overlay(rn, kind, raw.bloodline) : (rn.nodeOverlay ?? (otype ? (raw.nodeOverlay[otype] ?? null) : null));

    let options: AttributeOption[] | null = null;
    if (rn.isAttribute && Array.isArray(rn.options)) {
      options = (rn.options as { name: string; icon: string; stats: string[] }[]).map((o) => ({
        name: o.name,
        icon: o.icon,
        stats: o.stats ?? [],
      }));
    }

    nodes.set(rn.skill, {
      id: rn.skill,
      name: rn.name,
      stats: rn.stats ?? [],
      x,
      y,
      kind,
      asc: rn.ascendancyName ?? null,
      classesStart: rn.classesStart ?? null,
      group: gidx(rn.group),
      orbit: rn.orbit,
      icon: kind === "mastery" ? (rn.inactiveIcon ?? rn.icon) : rn.icon,
      activeIcon: kind === "mastery" ? (rn.activeIcon ?? null) : null,
      masteryEffects: kind === "mastery" && rn.masteryEffects?.length ? rn.masteryEffects.map((e) => ({ effect: e.effect, stats: e.stats ?? [] })) : null,
      links: [],
      flavour: rn.flavourText ?? null,
      switchable: rn.isSwitchable === true,
      isAttribute: rn.isAttribute === true,
      options,
      overlay,
      effect: rn.activeEffectImage ?? null,
      size,
      r: kind === "mastery" ? size.base : kind === "ascStart" ? 0 : overlay ? size.overlay : 0,
      // PassiveSpec.lua drops sub-sockets with a parent; PoB regenerates them inside a socketed cluster.
      hidden: rn.aliasPassiveSocket !== undefined || rn.isProxy === true || rn.expansionJewel?.parent != null,
    });
  }

  const edges: TEdge[] = [];
  const seen = new Set<string>();
  for (const rn of Object.values(raw.nodes)) {
    const a = nodes.get(rn.skill);
    if (!a) continue;
    for (const c of rn.connections ?? []) {
      const b = nodes.get(c.id);
      if (!b || b.id === a.id) continue;
      if (a.kind === "onlyImage" || b.kind === "onlyImage") continue;
      if (a.hidden || b.hidden) continue;
      a.links.push(b.id);
      b.links.push(a.id);
      // Masteries are logically linked to their wheel for allocation, but PoB
      // deliberately leaves that link out of the rendered connectors.
      if (a.kind === "mastery" || b.kind === "mastery") continue;
      if (a.asc !== b.asc) continue;
      if (a.classesStart || b.classesStart) continue;
      const key = a.id < b.id ? `${a.id}:${b.id}` : `${b.id}:${a.id}`;
      if (seen.has(key)) continue;
      seen.add(key);

      let arc: Arc | null = null;
      const orbitR = orbitRadii[Math.abs(c.orbit)];
      if (c.orbit !== 0 && orbitR) {
        const dx = b.x - a.x;
        const dy = b.y - a.y;
        const dist = Math.hypot(dx, dy);
        if (dist < orbitR * 2 && dist > 0) {
          const perp = Math.sqrt(orbitR * orbitR - (dist * dist) / 4) * (c.orbit > 0 ? 1 : -1);
          const cx = a.x + dx / 2 + perp * (dy / dist);
          const cy = a.y + dy / 2 - perp * (dx / dist);
          arc = minorArc(cx, cy, orbitR, a.x, a.y, b.x, b.y);
        }
      } else if (a.group === b.group && a.orbit === b.orbit && c.orbit === 0 && orbitRadii[a.orbit]) {
        const g = groupsArr[a.group]!;
        arc = minorArc(g.x, g.y, orbitRadii[a.orbit], a.x, a.y, b.x, b.y);
      }
      edges.push({ a: a.id, b: b.id, asc: a.asc, arc });
    }
  }

  // PoE1 group rings: the largest of orbits 1..3 in use picks the art, as in
  // PassiveTreeView.lua's renderGroup; ascendancy and proxy groups have none.
  const groups: TGroupArt[] = [];
  if (poe1) {
    const orbitsOf = new Map<number, Set<number>>();
    const skip = new Set<number>();
    for (const rn of Object.values(raw.nodes)) {
      const gi = gidx(rn.group);
      if (rn.ascendancyName || rn.isProxy) skip.add(gi);
      let s = orbitsOf.get(gi);
      if (!s) orbitsOf.set(gi, (s = new Set()));
      s.add(rn.orbit);
    }
    for (const [gi, s] of orbitsOf) {
      const g = groupsArr[gi];
      if (!g || skip.has(gi)) continue;
      if (s.has(3)) groups.push({ x: g.x, y: g.y, bg: "PSGroupBackground3", mirrored: true });
      else if (s.has(2)) groups.push({ x: g.x, y: g.y, bg: "PSGroupBackground2", mirrored: false });
      else if (s.has(1)) groups.push({ x: g.x, y: g.y, bg: "PSGroupBackground1", mirrored: false });
    }
  }

  const classes: TClass[] = raw.classes.map((c) => ({
    name: c.name,
    id: c.integerId,
    bg: c.background?.image ?? "",
    bgX: c.background?.x ?? 0,
    bgY: c.background?.y ?? 0,
    bgHalf: c.background?.width ?? 1500,
    activeHalf: c.background?.active?.width ?? (poe1 ? 0 : 2000),
    ringHalf: c.background?.bg?.width ?? (poe1 ? 0 : 2000),
    hubAsc: !poe1,
    area: poe1 ? (POE1_AREA[c.integerId] ?? null) : null,
    ascendancies: c.ascendancies
      .filter((a) => a.background)
      .map((a) => ({
        name: a.name,
        id: a.id,
        bg: a.background!.image,
        x: a.background!.x,
        y: a.background!.y,
        half: a.background!.width,
        replace: a.replace ?? null,
        replaceBy: a.replaceBy ?? null,
      })),
    startNode: classStart.get(c.name) ?? null,
  }));

  return {
    version,
    poe1,
    nodes,
    edges,
    classes,
    groups,
    classStart,
    bounds: { minX: raw.min_x, minY: raw.min_y, maxX: raw.max_x, maxY: raw.max_y },
  };
}

/**
 * The tree plus PoE1's cluster jewel subgraphs, which PoB generates from the
 * socketed jewels and positions itself. Straight connectors stand in for
 * PoB's arcs around the jewel.
 */
export function withDynamicNodes(base: TreeModel, dyn: DynamicNode[], dynGroups: DynamicGroup[] = []): TreeModel {
  if (!dyn.length) return base;
  // Cluster rings use the Alt art, chosen like the tree's own groups.
  const groups = base.groups.slice();
  for (const g of dynGroups) {
    const s = new Set(g.orbits);
    if (s.has(3)) groups.push({ x: g.x, y: g.y, bg: "GroupBackgroundLargeHalfAlt", mirrored: true });
    else if (s.has(2)) groups.push({ x: g.x, y: g.y, bg: "GroupBackgroundMediumAlt", mirrored: false });
    else if (s.has(1)) groups.push({ x: g.x, y: g.y, bg: "GroupBackgroundSmallAlt", mirrored: false });
  }
  const nodes = new Map(base.nodes);
  const edges = base.edges.slice();
  const seen = new Set<string>();
  for (const d of dyn) {
    const kind: NodeKind = d.type === "Notable" ? "notable" : d.type === "Keystone" ? "keystone" : d.type === "Socket" ? "socket" : "normal";
    const rn = { expansionJewel: d.expansion ? {} : undefined } as RawNode;
    const size = targetSizePoe1(rn, kind);
    const overlay = poe1Overlay(rn, kind);
    nodes.set(d.id, {
      id: d.id,
      name: d.name ?? "",
      stats: d.stats,
      x: d.x,
      y: d.y,
      kind,
      asc: null,
      classesStart: null,
      group: -1,
      orbit: 0,
      icon: d.icon ?? "",
      activeIcon: null,
      masteryEffects: null,
      links: [],
      flavour: null,
      switchable: false,
      isAttribute: false,
      options: null,
      overlay,
      effect: null,
      size,
      r: overlay ? size.overlay : 0,
      hidden: false,
    });
  }
  const dynIds = new Set(dyn.map((d) => d.id));
  for (const d of dyn) {
    const a = nodes.get(d.id)!;
    for (const id of d.links) {
      let b = nodes.get(id);
      if (!b || b.id === a.id) continue;
      const key = a.id < b.id ? `${a.id}:${b.id}` : `${b.id}:${a.id}`;
      if (seen.has(key)) continue;
      seen.add(key);
      a.links.push(b.id);
      if (!b.links.includes(a.id)) {
        // a tree node (the parent socket) belongs to the base model; copy before linking
        if (!dynIds.has(b.id)) {
          b = { ...b, links: [...b.links] };
          nodes.set(b.id, b);
        }
        b.links.push(a.id);
      }
      edges.push({ a: a.id, b: b.id, asc: null, arc: null });
    }
  }
  return { ...base, nodes, edges, groups };
}

/** Coarse spatial hash for hit testing. */
export class NodeIndex {
  private cell = 600;
  private buckets = new Map<string, TNode[]>();
  constructor(nodes: Iterable<TNode>) {
    for (const n of nodes) {
      if (n.r <= 0 || n.hidden) continue;
      const k = this.key(n.x, n.y);
      let b = this.buckets.get(k);
      if (!b) this.buckets.set(k, (b = []));
      b.push(n);
    }
  }
  private key(x: number, y: number) {
    return `${Math.floor(x / this.cell)}:${Math.floor(y / this.cell)}`;
  }
  nearest(x: number, y: number, filter?: (n: TNode) => boolean): TNode | null {
    const cx = Math.floor(x / this.cell);
    const cy = Math.floor(y / this.cell);
    let best: TNode | null = null;
    let bestD = Infinity;
    for (let i = -1; i <= 1; i++) {
      for (let j = -1; j <= 1; j++) {
        const b = this.buckets.get(`${cx + i}:${cy + j}`);
        if (!b) continue;
        for (const n of b) {
          if (filter && !filter(n)) continue;
          const d = Math.hypot(n.x - x, n.y - y);
          if (d <= n.r && d < bestD) {
            bestD = d;
            best = n;
          }
        }
      }
    }
    return best;
  }
}
